import Link from 'next/link';
import { ArrowLeft, Instagram, MessageCircle, ShieldCheck, Truck } from 'lucide-react';
import { Footer, Header, WhatsAppFloat } from '../../../components/site-chrome';

const data: Record<string, { name: string; type: string; price: string; image: string; description: string }> = {
  'Arsenal': { name: 'Arsenal Home jersey', type: 'Jerseys', price: 'Rs. 1,499', image: 'https://images.unsplash.com/photo-1579952363873-27f3bade9f55?auto=format&fit=crop&w=1200&q=85', description: 'Represent your colours with confidence. A lightweight, match-ready jersey made for long runs and louder celebrations.' },
  'midnight-striker': { name: 'Midnight Striker', type: 'Jerseys', price: 'Rs. 1,299', image: 'https://images.unsplash.com/photo-1526232761682-d26e03ac148e?auto=format&fit=crop&w=1200&q=85', description: 'Clean lines, serious energy. The Midnight Striker is an everyday favourite for training, street play and match day.' },
  'speedforce-elite': { name: 'Speedforce Elite', type: 'Boots', price: 'Rs. 4,999', image: 'https://images.unsplash.com/photo-1553778263-73a83bab9b0c?auto=format&fit=crop&w=1200&q=85', description: 'Made for quick feet and quicker decisions. A responsive pair for players who find space where others don’t.' },
  'street-play-boot': { name: 'Street Play Boot', type: 'Boots', price: 'Rs. 3,499', image: 'https://images.unsplash.com/photo-1511886929837-354d827aae26?auto=format&fit=crop&w=1200&q=85', description: 'Your reliable street-to-pitch pair. Comfortable, grippy and ready whenever the next game starts.' },
};
const wa = 'https://wa.me/9779869114712';
export default function ProductPage({ params }: { params: { slug: string } }) { const p = data[params.slug] || data['nepal-home-jersey']; return <main><div className="bg-ink text-white"><Header /><div className="mx-auto max-w-7xl px-5 pb-16 pt-32 lg:px-8"><Link href="/" className="mb-8 inline-flex items-center gap-2 text-sm text-white/70 hover:text-lime"><ArrowLeft className="h-4 w-4" /> Back to shop</Link><div className="grid gap-12 lg:grid-cols-2 lg:items-center"><div className="overflow-hidden rounded-[2rem] bg-orange"><img src={p.image} alt={p.name} className="aspect-square h-full w-full object-cover" /></div><div><p className="text-sm font-bold uppercase tracking-[.2em] text-lime">{p.type}</p><h1 className="mt-3 font-display text-5xl font-bold leading-none sm:text-7xl">{p.name}</h1><p className="mt-5 text-2xl font-bold">{p.price}</p><p className="mt-6 max-w-lg text-lg leading-8 text-white/70">{p.description}</p><div className="mt-8 flex flex-wrap gap-3"><Link href={wa} target="_blank" className="inline-flex items-center gap-2 rounded-full bg-lime px-6 py-3.5 font-bold text-ink transition hover:bg-white"><MessageCircle className="h-5 w-5" /> Contact on WhatsApp</Link><Link href="https://instagram.com/docosportswear" target="_blank" className="inline-flex items-center gap-2 rounded-full border border-white/25 px-6 py-3.5 font-bold transition hover:border-lime hover:text-lime"><Instagram className="h-5 w-5" /> DM on Instagram</Link></div><p className="mt-5 text-sm text-white/50">Contact in WhatsApp or Insta to order • Sizes and availability confirmed by DM</p><div className="mt-10 grid max-w-md grid-cols-2 gap-4 border-t border-white/15 pt-6 text-sm"><div className="flex gap-2"><ShieldCheck className="h-5 w-5 text-lime" /> Quality checked</div><div className="flex gap-2"><Truck className="h-5 w-5 text-lime" /> Kathmandu delivery</div></div></div></div></div></div><Footer /><WhatsAppFloat /></main>; }
